<?php

/**
 * Implements hook_privatemsg_form_alter().
 * Seuls le webmaster et l'admin peuvent modifier les destinataires des messages privés
 */
function bluestone_privatemsg_recipient_form_privatemsg_new_alter(&$form, &$form_state, $form_id) {
   $form['recipient']['#disabled'] = TRUE;
    if (bluestone_is_admin() OR bluestone_is_webmaster())
       $form['recipient']['#disabled'] = FALSE;
} 


